routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::any('adminer', '\Miroc\LaravelAdminer\AdminerController@index')->name('adminer');  // admin db mysql 



Route::get('/p/{id}/{segment?}', 'ShowPost')->name('showpost');
Route::get('/showsearch', 'ShowSearch')->name('showsearch');


//Route::any('pas', 'Pas')->name('pas');

Route::group(
    [
        'middleware' => [
            'auth'
        ],
        'namespace' => 'Cabinet',
        'prefix'    => 'cabinet',
        'as' => 'cabinet.'
    ],
    function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Index']);
        //Route::get('/showcatalog', ['as' => 'showcatalog', 'uses' => 'Index']);
        Route::get('/showcatalog/{slug1?}/{slug2?}', ['as' => 'showcatalog', 'uses' => 'ShowCatalog']);
        Route::get('/showcomments', ['as' => 'showcomments', 'uses' => 'ShowComments']);
        Route::get('/showrating', ['as' => 'showrating', 'uses' => 'ShowRating']);
        Route::get('/showfavorites/{slug1?}/{slug2?}', ['as' => 'showFavorites', 'uses' => 'ShowFavorites']);
        Route::get('/show-follows/{slug1?}/{slug2?}', ['as' => 'showFollows', 'uses' => 'ShowFollows']);

        Route::get('/user/follow', ['as' => 'follow', 'uses' => 'User\Follow']);
        Route::get('/user/unfollow', ['as' => 'unfollow', 'uses' => 'User\Unfollow']);
        Route::get('/user/is-private', ['as' => 'isprivate', 'uses' => 'User\IsPrivate']); //main.js
    

        Route::get('/get-last-items', ['as' => 'getLastItems', 'uses' => 'Photo\LastItems']);// main.js

        Route::post('/showcatalog/store', ['as'=>'dropzoneStore', 'uses'=>'Photo\DropzoneStore']);
        Route::post('/showcatalog/destroy', ['as'=>'dropzoneDestroy', 'uses'=>'Photo\DropzoneDestroy']);
        Route::post('/showcatalog/photomove', ['as'=>'dropzonePhotoMove', 'uses'=>'Photo\DropzonePhotoMove']);

        Route::post('/post/addposttofavorites', ['as'=>'addPostToFavorites', 'uses'=>'Post\AddPostToFavorites']);

        Route::post('/post/postlikeset', ['as'=>'postLikeSet', 'uses'=>'Post\PostLikeSet']);


        Route::post('/post/postdislikeset', ['as'=>'postDislikeSet', 'uses'=>'Post\PostDislikeSet']);


        Route::post('/post/postdisactive', ['as'=>'postDisActive', 'uses'=>'Post\PostDisActive']);


        Route::post('/comment/commentlikeset', ['as'=>'commentLikeSet', 'uses'=>'Comment\CommentLikeSet']);
        Route::post('/comment/commentdislikeset', ['as'=>'commentDislikeSet', 'uses'=>'Comment\CommentDislikeSet']);

        Route::post('/comment/update-comment', ['as'=>'updateComment', 'uses'=>'Comment\UpdateComment']);
        Route::post('/comment/add-comment-image', ['as'=>'addCommentImage', 'uses'=>'Comment\AddCommentImage']);

        Route::post('/comment/mark-as-viewed', ['as'=>'markAsViewed', 'uses'=>'Comment\MarkAsViewed']);

        Route::post('/post/updatepostcomment', ['as'=>'updatePostComment', 'uses'=>'Post\UpdatePostComment']);
        Route::post('/post/addcommentimage', ['as'=>'addPostCommentImage', 'uses'=>'Post\AddCommentImage']);
    }
);


//todo повесить middleware "ни для кого" - 404?
Route::resource('photos', 'Cabinet\Photo\Resource');

Route::delete('/tags', 'Cabinet\Tag\Resource@destroy');
Route::resource('tags', 'Cabinet\Tag\Resource');

Route::resource('comments', 'Cabinet\Comment\Resource');


// Route::get('/login-as/{login}', function ($login)
// {
//     switch ($login)
//     {
//         case 'lolik_89':
//             session(['clientId' => '64d03de3ea344a31b7fa496d0c9b6df2']);
//             session(['clientSecret' => '884be34ffbd54c308f38193ee757ee9f']);
//             break;
//         case 'artem.stepochkin':
//             session(['clientId' => 'b00a737d5e24463a9bdf425a5c452125']);
//             session(['clientSecret' => 'a5be9c22f25b445ab66a7273033e0008']);
//             break;
//         case 'v.voloshyn96':
//             session(['clientId' => '768aa50b31154e99b58bd3c2e002a0f5']);
//             session(['clientSecret' => '5b83c79bcd04476e87bc7f73648a6f60']);
//             break;
//         default: break;
//     }
//     return redirect()->back();
//     //return redirect()->route('socialAuth', 'instagram');
// });


Auth::routes();    //all  !!!!!





//OAuth routes
Route::get('auth/{driver}', ['as' => 'socialAuth', 'uses' => 'Auth\Social@redirectToProvider']);
Route::get('auth/{driver}/callback', ['as' => 'socialAuthCallback', 'uses' => 'Auth\Social@handleProviderCallback']);

Route::get('/setlocale/{locale}', function ($locale) {
    $locale = (\Illuminate\Support\Facades\File::isDirectory('../resources/lang/'.$locale)) ? $locale : App::getLocale();
    session(['lang' => $locale]);
    return redirect()->back();
});

Route::get('/{slug1?}/{slug2?}/{slug3?}/{slug4?}', 'Index')->name('index');  // SearchController

//Route::get('/REMOVE_THIS_ROUTE', 'ShowProfile')->name('showprofile');

resources/views/layouts/partials/filters.blade.php
    <div class="filters">
        <div class="select_wrap ">
            {{--<span class="filter_title select_title">{{ __('home.sort_by.'.request('by', (isset($withOnlyPosts) && $withOnlyPosts) ? 'only_posts' : 'instagram')) }}</span><i class="fa fa-angle-down" aria-hidden="true"></i>--}}
            <span class="filter_title select_title">ppp{{ __('home.sort_by.' . (!empty($defaults['filter1']) ? $defaults['filter1'] : $defaults['by'])) }}</span><i class="fa fa-angle-down" aria-hidden="true"></i>
            <div class="select">
                <ul>
                    <li><a href="{{ \App\Services\StringService::generateFiltersUrl($numOfLeftSlugs, ['by'=>'instagram'], $defaults) }}">tttt{{ __('home.sort_by.instagram') }}</a></li>
                    @if(isset($withOnlyPosts) && $withOnlyPosts)
                        {{--                        <li><a href="{{ request()->fullUrlWithQuery(['by'=>'only_posts']) }}">{{ __('home.sort_by.only_posts') }}</a></li>--}}
                        <li><a href="{{ \App\Services\StringService::generateFiltersUrl($numOfLeftSlugs, ['by'=>'only_posts'], $defaults) }}">{{ __('home.sort_by.only_posts') }}</a></li>
                    @endif
                    <li><a href="{{ \App\Services\StringService::generateFiltersUrl($numOfLeftSlugs, ['by'=>'im_likes'], $defaults) }}">{{ __('home.sort_by.im_likes') }}</a></li>
                    <li><a href="{{ \App\Services\StringService::generateFiltersUrl($numOfLeftSlugs, ['by'=>'rating'], $defaults) }}">{{ __('home.sort_by.rating') }}</a></li>
                    <li><a href="{{ \App\Services\StringService::generateFiltersUrl($numOfLeftSlugs, ['by'=>'favorites'], $defaults) }}">{{ __('home.sort_by.favorites') }}</a></li>
                    <li><a href="{{ \App\Services\StringService::generateFiltersUrl($numOfLeftSlugs, ['by'=>'by_comments'], $defaults) }}">{{ __('home.sort_by.by_comments') }}</a></li>
                </ul>
            </div>
        </div>
        <div class="select_wrap ">
            <span class="filter_title select_title">{{ __('home.time.' . (!empty($defaults['filter2']) ? $defaults['filter2'] : $defaults['on'])) }}</span><i class="fa fa-angle-down" aria-hidden="true"></i>
            <div class="select">
                <ul>
                    <li><a href="{{ \App\Services\StringService::generateFiltersUrl($numOfLeftSlugs, ['on'=>'all'], $defaults) }}">{{ __('home.time.all') }}</a></li>
                    <li><a href="{{ \App\Services\StringService::generateFiltersUrl($numOfLeftSlugs, ['on'=>'week'], $defaults) }}">{{ __('home.time.week') }}</a></li>
                    <li><a href="{{ \App\Services\StringService::generateFiltersUrl($numOfLeftSlugs, ['on'=>'month'], $defaults) }}">{{ __('home.time.month') }}</a></li>
                </ul>
            </div>
        </div>
    </div>

resources/views/layouts/partials/footer.blade.php
	{{--@if(session('message', ''))--}}
		{{--<script type="text/javascript">--}}
            {{--setTimeout(function(){--}}
                {{--//Что-то из этого срабатывает--}}
                {{--window.location.reload(1);--}}
                {{--location.reload;--}}
                {{--window.location.reload();--}}
                {{--window.location=window.location;--}}
                {{--window.location.reload(true); // use this if you want to remove cache--}}
            {{--}, 5000);--}}
		{{--</script>--}}
		{{--<div class="snackbar active">{{ session('message', '') }}</div>--}}
	{{--@else--}}
		{{--<div class="snackbar"></div>--}}
	{{--@endif--}}

	<div class="snackbar"></div>

	<input type="hidden" class="sm_need_auth" value="{{ __('layout.need_auth_for_action') }}" />
	<input type="hidden" class="get_params" value="{{ request()->getQueryString() }}" />

<b> 444444    {{ request()->getQueryString() }} </b>
        
        
	<div id="preview-template" class="hidden">
		<div class="add_img_wrap dragbox dz-preview dz-file-preview">
			<img class="dragbox-content" src="{{ asset('uploads/no-image.png') }}" data-dz-thumbnail alt="thumb" />
			<span class="del_photos"><i class="fa fa-times" aria-hidden="true"></i></span>
		</div>
	</div>
	<input id="current_page" type="text" value="1" hidden>
	<footer>
		<div class="footer container">
			<p>{{ __('layout.rights') }}</p>
			<a href="#">{{ __('layout.write_to_us') }}</a>
		</div>
	</footer>

resources/views/layouts/partials/header.blade.php
    <header>
        <div class="header container">
            <a class="logo" href="{{ url('/') }}"><img src="{{ asset('img/logo.png') }}" alt="logo"></a>

            @include('layouts.partials.search')

            <div class="menu">
                <i class="fa fa-bars menu_mob_btn" aria-hidden="true"></i>
                <div class="nav_menu">
                    <div class="select_wrap lang">
                        <span class="select_title">GG{{ app()->getLocale() }}</span>
                        <div class="select">
                            <ul>
                                <li><a href="{{ url('/setlocale/eng') }}">Eng</a></li>
                                <li><a href="{{ url('/setlocale/rus') }}">Rus</a></li>
                            </ul>
                        </div>
                    </div>

                    @if(Auth::check())
                    <div class="menu_icons">
                        <a class="{{ route('cabinet.showrating') == request()->url() ? 'be_active' : '' }}" href="{{ route('cabinet.showrating') }}">
                            <i class="flaticon-star" aria-hidden="true"></i>
                            <div class="rate_count">{{ Auth::user()->rating  }}</div>
                        </a>
                        <a class="{{ url('/') == request()->url() ? 'be_active' : '' }}" href="{{ url('/') }}"><i class="flaticon-house" aria-hidden="true"></i></a>
                        <a class="{{ route('cabinet.showFavorites') == request()->url() ? 'be_active' : '' }}" href="{{ route('cabinet.showFavorites') }}"><i class="flaticon-heart" aria-hidden="true"></i></a>
                        <a class="{{ route('cabinet.showcomments') == request()->url() ? 'be_active' : '' }}" href="{{ route('cabinet.showcomments') }}">
                            <i class="flaticon-edit" aria-hidden="true"></i>
                            @if($commentsCount = \App\Models\Comment::getNewCommentsForUser(Auth::user())->count())
                                <div class="bage">{{ $commentsCount }}</div>
                            @endif
                        </a>
                        <a class="{{ route('cabinet.showcatalog') == request()->url() ? 'be_active' : '' }}" href="{{ route('cabinet.showcatalog') }}"><i class="flaticon-picture-with-frame" aria-hidden="true"></i></a>
                        <a class="{{ route('cabinet.index') == request()->url() ? 'be_active' : '' }}" href="{{ route('cabinet.index') }}"><i class="flaticon-avatar" aria-hidden="true"></i></a>
                    </div>
                    @else
                        <a  href="{{ route('register') }}">
                            <button href="{{ route('register') }}" class="btn_for_auth">{{ __('auth.register_btn') }}</button>
                        </a>
                        <a  href="{{ route('login') }}">
                            <button href="{{ route('login') }}" class="btn_for_auth">{{ __('auth.login_btn') }}</button>
                        </a>
                    @endif

                </div>
            </div>
        </div>
    </header>

resources/views/layouts/partials/icons.blade.php
    <div class="icons">
      
        <input class="post_id" type="text" hidden value="{{ $post->id }}">
        
        <div class="icon_wrap like3"><i class="flaticon-like icon_js {{ $post->isUserLikeFound() ? 'active' : '' }}" data-value="like" aria-hidden="true"></i><span>{{ $post->likes }}</span></div>
        <div class="icon_wrap dislike4"><i class="flaticon-dislike icon_js {{ $post->isUserDislikeFound() ? 'active' : '' }}" data-value="dislike" aria-hidden="true"></i><span>{{ $post->dislikes }}</span></div>
        <div class="icon_wrap favor"><i class="flaticon-heart icon_js @if(Auth::check()) {{ Auth::user()->isUserFavoritesFound($post) ? 'active' : '' }} @endif" data-value="favor" aria-hidden="true"></i><span>{{ $post->favorites_count }}</span></div>
        <div class="icon_wrap rating"><i class="flaticon-star" data-value="rating" aria-hidden="true"></i><span>{{ $post->rating }}</span></div>
        
         <div class="icon_wrap dislike_post"><i class="flaticon-dislike icon_js " data-value="is_empty" aria-hidden="true"></i><span>{{ $post->is_empty }}</span></div>
        

        <div class="icon_wrap"><a href="{{ route('showpost', $post->getLinkPart()) }}"><i class="flaticon-edit" aria-hidden="true"></i></a><span>{{ $post->getCommentsCount() }}</span></div>
        
        
    </div>

resources/views/layouts/partials/modal-for-thumbs.blade.php
    <div class="modal hidden">
        
        <div class="modal_back"><i class="fa fa-times close_modal" aria-hidden="true"></i></div>
        <div class="modal_content">
            <div class="owl-carousel owl-theme modal_slider">
                    @if(!empty($carouselSrcs))
                    @foreach($carouselSrcs as $src)
                    <div class="slider-item">
                        <div class="slide_img">
                            <img src="{{ $src }}" alt="slide"/>
                        </div>
                        <div class="slide_text_wrap">
                            <span class="photo_title">{{ __('home.modal_instagram_photo') }}</span>
                            <div class="slide_text_header">
                                <div class="slide_text_img">
                                     <p>carouselSrcs_modal_for_thumb</p>
                                    <a href="{{ route('index', $post->user->i_login) }}"><img src="{{ $post->user->getAvatarSrc() }}" alt="user_pick"></a>
                                </div>
                                <div class="slide_header_text">
                                    <a href="{{ route('index', $post->user->i_login) }}"><p class="slide_username">{{ $post->user->i_login }}</p></a>
                                    <p></p>
                                </div>
                            </div>
                            @include('layouts.partials.modal-right', ['post'=>$post])
                        </div>
                    </div>
                    @endforeach
                    @endif
               
                    @foreach($imagePhotos as $photo)
                        @if($loop->first && is_object($photo) && $photo->isInstagramCarousel()) @continue @endif
                        <div class="slider-item">
                            <div class="slide_img">
                                <img src="{{ isset($mode) && $mode == 'carousel' ? $photo : $photo->getImageSrc() }}" alt="slide"/>
                            </div>
                            <div class="slide_text_wrap">
                                 <p>carouselSrcs_modal_for_thumb</p>
                                <span class="photo_title">{{ is_object($photo) && $photo->isSiteImage() ? __('home.modal_additional_photo') : __('home.modal_instagram_photo') }}</span>
                                <div class="slide_text_header">
                                    <div class="slide_text_img">
                                        <a href="{{ route('index', $post->user->i_login) }}"><img src="{{ $post->user->getAvatarSrc() }}" alt="user_pick"></a>
                                    </div>
                                    <div class="slide_header_text">
                                        <a href="{{ route('index', $post->user->i_login) }}"><p class="slide_username">{{ $post->user->i_login }}</p></a>
                                        <p></p>
                                    </div>
                                </div>
                                @include('layouts.partials.modal-right', ['post'=>$post])
                            </div>
                        </div>
                    @endforeach
            </div>
        </div>
    </div>

resources/views/layouts/partials/modal-right.blade.php
<div class="slide_text">
    <p>hello world55555</p>
    <div class="slide_comment">
        @if(!empty($post->description->content))
        <a href="{{ route('index', $post->user->i_login) }}"><span class="slide_username">{{ $post->user->i_login }}</span></a>
        {!! $post->description->content !!}
        @else
        <p>{{ __('layout.post_description_empty') }}</p>
        @endif
        @foreach($post->tags as $tag)
        <a href="{{ route('index', ['tag', $tag->name]) }}"><span class="hashtag">{{ $tag->name }}</span></a>
        @endforeach
        <br /><br />
        @forelse($post->comments as $comment)
        <a href="{{ route('index', $comment->user->i_user) }}"><span class="slide_username">{{ $comment->user->i_login }}</span></a>
        <p>{!! $comment->content !!}</p>
        @empty
        <p>{{ __('layout.post_comments_empty') }}</p>
        @endforelse


        <i class="fa fa-times delete_comment hidden" aria-hidden="true"></i>
    </div>
</div>
<div class="slide_text_footer">
    <span>{{ $post->user->i_login }}</span>
    <i class="fa fa-heart" aria-hidden="true"></i><span>{{ $post->i_likes_count }}</span>
    <i class="fa fa-comment" aria-hidden="true"></i><span>{{ $post->i_comments_count }}</span>
</div>

resources/views/layouts/partials/photo-info.blade.php
    <div class="photo_info">
        <div>
            <span><a href="{{ route('index', $post->user->i_login) }}">{{ $post->user->i_login }}</a></span>
            <span><i class="fa fa-heart" aria-hidden="true"></i>{{ $post->i_likes_count }}</span>
            <span><i class="fa fa-comment" aria-hidden="true"></i>{{ $post->i_comments_count }}</span>
        </div>
        <div><i class="fa fa-star-o" aria-hidden="true"></i>{{ $post->user->rating }}</div>
    </div>

resources/views/layouts/partials/posts-list.blade.php
@section('content')
    @parent
    @include('layouts.partials.filters')
    @if(count($posts) > 0)
        <div class="post_title">
            <h1 class="post_title_item instagram_photo">rrrr{{ __('home.instagram') }}</h1>
            <h2 class="post_title_item add_photos">{{ __('home.additional_photo') }}</h2>
            <h2 class="post_title_item comment">{{ __('home.comments') }}</h2>
        </div>
        @include('home.partials.pagination-item', $posts)
    @else
        <div style="padding-left: 110px; padding-top: 40px">kkk{{ __('home.posts_not_found') }}</div>
    @endif
@endsection

@section('additionalDivs')
    @parent
    @if(!empty($posts) && $posts->currentPage() != $posts->lastPage())
        <button class="btn show_more_btn">{{ __('home.show_more') }}</button>
    @endif
@endsection

resources/views/layouts/partials/search.blade.php
    <div class="search">
         <form method="get" action="{{ route('showsearch') }}"> 
            <input id="search" type="text" name="s" placeholder="{{ __('layout.search_placeholder') }}" />
        </form> 
    </div>

resources/views/layouts/partials/sync-status.blade.php
<section class="sync_status {{ Auth::user()->getSyncStatus() }}">
    @switch(Auth::user()->getSyncStatus())
        @case('is-private')
            {{ __('layout.sync_status_is-private') }}
        @break;

        @case('in-progress')
            {{ __('layout.sync_status_in-progress') }}
        @break;

        @case('done')
            {{ __('layout.sync_status_done', ['date' => Auth::user()->getSyncedAt()]) }}
        @break;

        @case('error')
            {{ __('layout.sync_status_error') }}
        @break;
    @endswitch    
</section>    

resources/views/layouts/partials/tags.blade.php
@if(count($tags))
    <div class="tags">
        @forelse($tags as $tag)
            <a href="{{ route('index', ['tag', $tag->name])  }}">{{ $tag->name }}</a>
        @empty
            {{--{{ __('home.no_tags') }}--}}
        @endforelse
    </div>
@endif

resources/views/layouts/partials/user.blade.php
    <div class="user">
        <div class="user_pick">
            <img src="{{ $user->getAvatarSrc() }}" alt="user_pick">
        </div>
        <div class="user_info">
            <h1 class="user_info_item user_name"><span>{{ $user->i_login }}</span><span>{{ $user->i_real_name }}</span></h1>
            <div class="user_info_item">
                <div class="user_info_descr_wrap">
                    <div class="user_info_title">
                        <span>{{ __('cabinet.instagram') }}</span>
                    </div>
                    <div class="user_info_descr">
                        <div><span>{{ $user->i_publications }}</span> {{ __('cabinet.instagram_media') }}</div>
                        <div><span>{{ $user->i_count_subscribers }}</span> {{ __('cabinet.followers_count') }}</div>
                        <div><span>{{ $user->i_count_subscribes }}</span> {{ __('cabinet.follows_count') }}</div>
                    </div>
                </div>
                @if(Auth::check() && Auth::user()->id != $user->id)
                <button class="btn snack_js">{{ __('cabinet.follow_on_instagram') }}</button>
                @endif
            </div>
            <div class="user_info_item">
                <div class="user_info_descr_wrap">
                    <div class="user_info_title">
                        <span>{{ __('cabinet.our_instagram') }}</span>
                    </div>
                    <div class="user_info_descr">
                        <div><span><i class="fa fa-star-o" aria-hidden="true"></i> {{ $user->rating }}</span> {{ __('cabinet.rating') }}</div>
                        <div><span>{{ $user->getAllOnlyPosts()->count() }}</span> {{ __('cabinet.posts') }}</div>
                        <div><span>{{ $user->followingUsers()->count() }}</span> {{ __('cabinet.followers_count') }}</div>
                        <div><span>{{ $user->getUserFavoritesCount() }}</span> {{ __('cabinet.favorites_count') }}</div>
                    </div>
                </div>

                @if(Auth::check() && Auth::user()->id != $user->id)
                    @if(!Auth::user()->isFollower($user))
                        <a href="{{ route('cabinet.follow', ['id'=>$user->id]) }}" class="btn snack_js">{{ __('cabinet.follow_on_site') }}</a>
                    @else
                        <a href="{{ route('cabinet.unfollow', ['id'=>$user->id]) }}" class="btn snack_js">{{ __('cabinet.unfollow_on_site') }}</a>
                    @endif
                @endif
            </div>
        </div>
    </div>