routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::any('adminer', '\Miroc\LaravelAdminer\AdminerController@index')->name('adminer');  // admin db mysql 



Route::get('/p/{id}/{segment?}', 'ShowPost')->name('showpost');
Route::get('/showsearch', 'ShowSearch')->name('showsearch');


//Route::any('pas', 'Pas')->name('pas');

Route::group(
    [
        'middleware' => [
            'auth'
        ],
        'namespace' => 'Cabinet',
        'prefix'    => 'cabinet',
        'as' => 'cabinet.'
    ],
    function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Index']);
        //Route::get('/showcatalog', ['as' => 'showcatalog', 'uses' => 'Index']);
        Route::get('/showcatalog/{slug1?}/{slug2?}', ['as' => 'showcatalog', 'uses' => 'ShowCatalog']);
        Route::get('/showcomments', ['as' => 'showcomments', 'uses' => 'ShowComments']);
        Route::get('/showrating', ['as' => 'showrating', 'uses' => 'ShowRating']);
        Route::get('/showfavorites/{slug1?}/{slug2?}', ['as' => 'showFavorites', 'uses' => 'ShowFavorites']);
        Route::get('/show-follows/{slug1?}/{slug2?}', ['as' => 'showFollows', 'uses' => 'ShowFollows']);

        Route::get('/user/follow', ['as' => 'follow', 'uses' => 'User\Follow']);
        Route::get('/user/unfollow', ['as' => 'unfollow', 'uses' => 'User\Unfollow']);
        Route::get('/user/is-private', ['as' => 'isprivate', 'uses' => 'User\IsPrivate']); //main.js
    

        Route::get('/get-last-items', ['as' => 'getLastItems', 'uses' => 'Photo\LastItems']);// main.js

        Route::post('/showcatalog/store', ['as'=>'dropzoneStore', 'uses'=>'Photo\DropzoneStore']);
        Route::post('/showcatalog/destroy', ['as'=>'dropzoneDestroy', 'uses'=>'Photo\DropzoneDestroy']);
        Route::post('/showcatalog/photomove', ['as'=>'dropzonePhotoMove', 'uses'=>'Photo\DropzonePhotoMove']);

        Route::post('/post/addposttofavorites', ['as'=>'addPostToFavorites', 'uses'=>'Post\AddPostToFavorites']);

        Route::post('/post/postlikeset', ['as'=>'postLikeSet', 'uses'=>'Post\PostLikeSet']);


        Route::post('/post/postdislikeset', ['as'=>'postDislikeSet', 'uses'=>'Post\PostDislikeSet']);


        Route::post('/post/postdisactive', ['as'=>'postDisActive', 'uses'=>'Post\PostDisActive']);


        Route::post('/comment/commentlikeset', ['as'=>'commentLikeSet', 'uses'=>'Comment\CommentLikeSet']);
        Route::post('/comment/commentdislikeset', ['as'=>'commentDislikeSet', 'uses'=>'Comment\CommentDislikeSet']);

        Route::post('/comment/update-comment', ['as'=>'updateComment', 'uses'=>'Comment\UpdateComment']);
        Route::post('/comment/add-comment-image', ['as'=>'addCommentImage', 'uses'=>'Comment\AddCommentImage']);

        Route::post('/comment/mark-as-viewed', ['as'=>'markAsViewed', 'uses'=>'Comment\MarkAsViewed']);

        Route::post('/post/updatepostcomment', ['as'=>'updatePostComment', 'uses'=>'Post\UpdatePostComment']);
        Route::post('/post/addcommentimage', ['as'=>'addPostCommentImage', 'uses'=>'Post\AddCommentImage']);
    }
);


//todo повесить middleware "ни для кого" - 404?
Route::resource('photos', 'Cabinet\Photo\Resource');

Route::delete('/tags', 'Cabinet\Tag\Resource@destroy');
Route::resource('tags', 'Cabinet\Tag\Resource');

Route::resource('comments', 'Cabinet\Comment\Resource');


// Route::get('/login-as/{login}', function ($login)
// {
//     switch ($login)
//     {
//         case 'lolik_89':
//             session(['clientId' => '64d03de3ea344a31b7fa496d0c9b6df2']);
//             session(['clientSecret' => '884be34ffbd54c308f38193ee757ee9f']);
//             break;
//         case 'artem.stepochkin':
//             session(['clientId' => 'b00a737d5e24463a9bdf425a5c452125']);
//             session(['clientSecret' => 'a5be9c22f25b445ab66a7273033e0008']);
//             break;
//         case 'v.voloshyn96':
//             session(['clientId' => '768aa50b31154e99b58bd3c2e002a0f5']);
//             session(['clientSecret' => '5b83c79bcd04476e87bc7f73648a6f60']);
//             break;
//         default: break;
//     }
//     return redirect()->back();
//     //return redirect()->route('socialAuth', 'instagram');
// });


Auth::routes();    //all  !!!!!





//OAuth routes
Route::get('auth/{driver}', ['as' => 'socialAuth', 'uses' => 'Auth\Social@redirectToProvider']);
Route::get('auth/{driver}/callback', ['as' => 'socialAuthCallback', 'uses' => 'Auth\Social@handleProviderCallback']);

Route::get('/setlocale/{locale}', function ($locale) {
    $locale = (\Illuminate\Support\Facades\File::isDirectory('../resources/lang/'.$locale)) ? $locale : App::getLocale();
    session(['lang' => $locale]);
    return redirect()->back();
});

Route::get('/{slug1?}/{slug2?}/{slug3?}/{slug4?}', 'Index')->name('index');  // SearchController

//Route::get('/REMOVE_THIS_ROUTE', 'ShowProfile')->name('showprofile');

resources/views/home/partials/comment.blade.php
<div class="post_comment {{ $parent_id != 0 ? 'comment_answer' : '' }}"><span id="comment{{ $comment->id }}"></span>
   <div class="post_comment_hader">
        <span class="post_comment_rate">0</span>

        <span>
			<i class="fa fa-arrow-down dislike_btn" aria-hidden="true"></i>
            <i class="fa fa-arrow-up like_btn" aria-hidden="true"></i>
		</span>

	<p>comment from response controller to JSON</> 
        <img src="{{ $comment->user->getAvatarSrc() }}" alt="user_pick">

        <span class="post_comment_autor"><a href="{{ route('index', $comment->user->i_login) }}">{{ $comment->user->i_login }}</a></span>
        <span>{{ $comment->user->rating }}</span>
        <span>{{ $comment->getFormattedTimeAgoString() }}</span>
    </div>

    <p>{!! $comment->content !!}</p>

    <div class="comment reply_block hidden">
        <div class="comment_block">
            <input type="hidden" name="post_id" value="{{ $post->id }}" />
            <input type="hidden" name="comment_id" value="{{ $comment->id }}" />
            <input type="hidden" name="parent_id" value="{{ $parent_id }}" />
            <div class="comment_text_field text_container" contenteditable="true"></div>
            <div class="comment_action_block">
                <div class="comment_action_icons hidden">
                    <i class="flaticon-piggy-bank" aria-hidden="true"></i>
                    <i class="flaticon-musical-note" aria-hidden="true"></i>
                    <i class="flaticon-chat" aria-hidden="true"></i>
                    <i class="flaticon-headphones" aria-hidden="true"></i>
                </div>

                <div class="comment_action_btn_block">
                    <i class="flaticon-smile smiles_dock_btn" aria-hidden="true"></i>
                    <i class="flaticon-photo-camera upload_photo_btn" aria-hidden="true"></i>
                </div>

                <div class="comment_modal hidden">
                    <span>{{ __('cabinet.youtube_link') }}</span>
                    <input type="text" name="youtube_link" placeholder="{{ __('cabinet.paste_link') }}">
                    <button class="upload_btn upload_video_js">{{ __('cabinet.upload_video') }}</button>
                    <form method="post" class="ajax_form" action="{{ route('cabinet.addCommentImage') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <input type="hidden" name="comment_id" value="" />
                        <span>{{ __('cabinet.upload_image') }}</span>
                        <label class="label_upload" for="upload{{ $comment->id }}">{{ __('cabinet.choose_file') }}</label>
                        <input id="upload{{ $comment->id }}" class="upload_photo_input_js" type="file" accept="image/*" name="imgs[]" multiple hidden>
                        <input class="upload_btn" type="submit" value="{{ __('cabinet.upload') }}" />
                    </form>
                </div>
            </div>

            @if($parent_id == 0)
                <div class="comment_btn send_btn send_btn_js">{{ __('home.comment_send') }}</div>
                <div class="comment_btn cansel_btn cancel_btn_js">{{ __('home.comment_cancel') }}</div>
            @endif
        </div>
    </div>
    @if($parent_id == 0)
        <div class="comment_btn reply_btn">{{ __('home.comment_answer') }}</div>
    @endif
</div>

resources/views/home/partials/modal-items.blade.php
<div class="slider-item">
    <div class="slide_img">
        <img src="{{ $src }}" alt="slide" data-index="{{ $y }}" />
    </div>
    <div class="slide_text_wrap">
        <span class="photo_title">{{ __('home.modal_instagram_photo') }}</span>
        <div class="slide_text_header">
            <div class="slide_text_img">
                <a href="{{ route('index', $post->user->i_login) }}"><img src="{{ $post->user->getAvatarSrc() }}" alt="{{ $post->user->i_login }}"></a>
            </div>
            <div class="slide_header_text">
                <a href="{{ route('index', $post->user->i_login) }}"><p class="slide_username">{{ $post->user->i_login }}</p></a>
            </div>
            <span class="slide_header_date">
                {{ date('d.m.Y H:i:s', $post->created_at->timestamp) }}
            </span>
        </div>
        @include('layouts.partials.modal-right', ['post'=>$post])
    </div>
</div>

resources/views/home/partials/modal-with-stack-items.blade.php
    <div class="modal hidden">
        <div class="modal_back"><i class="fa fa-times close_modal" aria-hidden="true"></i></div>
        <div class="modal_content">
            <div class="owl-carousel owl-theme modal_slider">

                    @stack('modal-item')

            </div>
        </div>
    </div>

resources/views/home/partials/modal.blade.php
    <div class="modal hidden">
        <div class="modal_back"><i class="fa fa-times close_modal" aria-hidden="true">modal_back_A</i></div>
        <div class="modal_content">
            <div class="owl-carousel owl-theme modal_slider">

                    @if(!empty($carouselSrcs))
                    @php $c = 0; @endphp
                    @foreach($carouselSrcs as $src)
                    @php $c++; @endphp
                    <div class="slider-item">
			<h1>slideimg222222</h1>
                        <div class="slide_img">
                            <img src="{{ $src }}" data-index="{{ $c }}" alt="slide"/>
                        </div>
                        <div class="slide_text_wrap">
                            <span class="photo_title">{{ __('home.modal_instagram_photo') }}</span>
                            <div class="slide_text_header">
                                <div class="slide_text_img">
                                    <a href="{{ route('index', $post->user->i_login) }}"><img src="{{ $post->user->getAvatarSrc() }}" alt="user_pick"></a>
                                </div>
                                <div class="slide_header_text">
                                    <a href="{{ route('index', $post->user->i_login) }}"><p class="slide_username">{{ $post->user->i_login }}</p></a>
                                </div>
                                <span class="slide_header_date">
                                    {{ date('d.m.Y H:i:s', $post->created_at->timestamp) }}
                                </span>
                            </div>
                            @include('layouts.partials.modal-right', ['post'=>$post])
                        </div>
                    </div>
                    @endforeach
                    @endif

                    @php $c = 0; @endphp
                    @foreach($imagePhotos as $photo)
                        @php $c++; @endphp
                        @if($loop->first && is_object($photo) && $photo->isInstagramCarousel()) @continue @endif
                        <div class="slider-item">
                            <div class="slide_img">
                                <img src="{{ isset($mode) && $mode == 'carousel' ? $photo : $photo->getImageSrc() }}" data-index="{{ $c }}" alt="slide"/>
                            </div>
                            <div class="slide_text_wrap">
                                <span class="photo_title">{{ is_object($photo) && $photo->isSiteImage() ? __('home.modal_additional_photo') : __('home.modal_instagram_photo') }}</span>
                                <div class="slide_text_header">
                                    <div class="slide_text_img">
                                        <a href="{{ route('index', $post->user->i_login) }}"><img src="{{ $post->user->getAvatarSrc() }}" alt="user_pick"></a>
                                    </div>
                                    <div class="slide_header_text">
                                        <a href="{{ route('index', $post->user->i_login) }}"><p class="slide_username">{{ $post->user->i_login }}</p></a>
                                    </div>
                                    <span class="slide_header_date">
                                        @if(is_object($photo) && $photo->isSiteImage())
                                            {{ date('d.m.Y H:i:s', $photo->created_at->timestamp)  }}
                                        @elseif(is_object($photo) && !$photo->isSiteImage())
                                            {{ date('d.m.Y H:i:s', $photo->i_created_time) }}
                                        @else
                                            {{ date('d.m.Y H:i:s', $post->created_at->timestamp) }}
                                        @endif
                                        {{--{{ is_object($photo) && $photo->isSiteImage() ? date('d.m.Y H:i:s', $photo->created_at->timestamp) : date('d.m.Y H:i:s', $photo->i_created_time) }}--}}
                                    </span>
                                </div>
                                @include('layouts.partials.modal-right', ['post'=>$post])
                            </div>
                        </div>
                    @endforeach









                     @php $c = 0; @endphp
                



            </div>
        </div>
    </div>

resources/views/home/partials/pagination-item.blade.php
@forelse($posts as $post)
    <div id="post{{ $post->id }}" class="post modal_block">
        @php $x=0; @endphp
        <div class="post_item_block instagram_photo">
            {{--<h2 class="post_title_item_mob">{{ __('home.instagram') }}</h2>--}}
            <h2 class="post_title_item_mob">modal_block{{ $post->user->i_login }}</h2>
            @include('layouts.partials.icons', ['post'=>$post])
            <div class="photo">
                <div class="photo_wrap">
                    <div class="loader">
                        <div class="spiner"></div>
                    </div>
                    @php $carouselSrcs = []; @endphp

                    @foreach($post->instagramPhotos()->get() as $photo)
                        <div class="owl-carousel owl-theme instagram_slider">
                        @if($photo->isInstagramImage())
                            @php $x++; @endphp
                            <img class="open_modal owl-lazy" src="{{ $photo->getThumbnailSrc() }}" data-src="{{ $photo->getThumbnailSrc() }}"  data-index="{{ $x }}" alt="inst_img">
                        @endif

                        @if($photo->isInstagramCarousel())
                                @foreach($photo->getInstagramCarouselSrcs(true) as $src)
                                    @php $x++; @endphp
                                    @php $carouselSrcs[] = $src; @endphp
                                    <div class="slider-item">
                                        {{-- <img class="open_modal" {{ $side['isEqual'] ? '' : $side['biggestSide'] . '=' . '' . $side['number'] . '' }} src="{{ $src }}" data-index="{{ $x }}" alt="inst_img">--}}
                                        <img class="open_modal owl-lazy" src="{{ $src }}"  data-src="{{ $src }}" data-index="{{ $x }}" alt="inst_img">
                                    </div>
                                @endforeach
                            <div class="instagram_album_ico">
                                <i class="fa fa-clone" aria-hidden="true"></i>
                            </div>
                        @endif

                        @forelse($post->imagePhotos()->get() as $photo)
                            @php $x++; @endphp

                            <img class="open_modal owl-lazy" src="{{ $photo->getImageSrc() }}" data-src="{{ $photo->getImageSrc() }}" data-index="{{ $x }}" alt="add_img">
                        @empty
                            {{--{{ __('home.no_add') }}--}}
                        @endforelse

                        </div>
                    @endforeach
                </div>
                @include('layouts.partials.photo-info', ['post'=>$post])
            </div>
            
            
            
            
            
            
            
            
        </div>
        {{--@if($post->imagePhotos()->count())--}}
        <div class="post_item_block add_photos">
            @if($post->imagePhotos()->count())
                <h2 class="post_title_item_mob">{{ __('home.additional_photo') }}</h2>
            @endif
            <div class="photos_block">
                @forelse($post->imagePhotos()->get() as $photo)
                    @php $x++; @endphp
                    <div class="add_img_wrap">
                        <img class="open_modal" src="{{ $photo->getThumbnailSrc() }}" data-index="{{ $x }}" alt="add_img" thumb="true">
                    </div>
                @empty
                    {{--{{ __('home.no_add') }}--}}
                @endforelse
            </div>
            @if(!empty($carouselSrcs))
                @include('home.partials.modal', ['carouselSrcs'=>$carouselSrcs, 'imagePhotos' => $post->imagePhotos, 'post'=>$post])
            @else
                @include('home.partials.modal', ['imagePhotos' => $post->instagramAndImagePhotos, 'post'=>$post])
            @endif
        </div>
        {{--@endif--}}

{{--        @if(($content = $post->description->content) || ($post->tags()->count()))--}}

        <div class="post_item_block comment">
            @if(($content = $post->description->content))
                <h2 class="post_title_item_mob">{{ __('home.comments') }}</h2>
            @endif
            <div class="text">
                {{--<div class="{{ $post->description->getDescriptionLength() > 500 ? 'text_wrap' : '' }}">{!! $post->description->getSmallDescription(500) !!}</div>--}}
                <div class="text_wrap">{!! $post->description->content !!}</div>
                <a href="{{ route('showpost', $post->getLinkPart()) }}">{{ __('home.read_more') }}</a>
            </div>
            @include('layouts.partials.tags', ['tags'=>$post->tags])
        </div>

        {{--@endif--}}

    </div>
@empty
@endforelse

resources/views/home/partials/replies.blade.php
@foreach($replies as $reply)
    <div class="post_comment comment_answer"><span id="comment{{ $reply->id }}"></span>
        <div class="post_comment_hader">
            <span class="post_comment_rate {{ $reply->rating > 0  ? 'positive' : ($reply->rating != 0 ? 'negative' : '') }}">{{ $reply->rating }}</span>

            <span>
                <i class="fa fa-arrow-down dislike_btn {{ $reply->isUserDislikeFound() ? 'active' : '' }}" aria-hidden="true"></i>
                <i class="fa fa-arrow-up like_btn {{ $reply->isUserLikeFound() ? 'active' : '' }}" aria-hidden="true"></i>
			</span>

            <img src="{{ $reply->user->getAvatarSrc() }}" alt="user_pick">

            <span class="post_comment_autor"><a href="{{ route('index', $reply->user->i_login) }}">{{ $reply->user->i_login }}</a></span>
            <span>{{ $reply->user->rating }}</span>
            <span>{{ $reply->getFormattedTimeAgoString() }}</span>
        </div>

        <p>{!! $reply->content !!}</p>

        <div class="comment reply_block hidden">
            <div class="comment_block">
                <input type="hidden" name="post_id" value="{{ $post->id }}" />
                <input type="hidden" name="comment_id" value="{{ $reply->id }}" />
                <input type="hidden" name="parent_id" value="{{ $reply->parent->id }}" />

                <div class="comment_text_field text_container" contenteditable="true"></div>

                <div class="comment_action_block">
                    <div class="comment_action_icons hidden">
                        <i class="flaticon-piggy-bank" aria-hidden="true"></i>
                        <i class="flaticon-musical-note" aria-hidden="true"></i>
                        <i class="flaticon-chat" aria-hidden="true"></i>
                        <i class="flaticon-headphones" aria-hidden="true"></i>
                    </div>
                    <div class="comment_action_btn_block">
                        <i class="flaticon-smile smiles_dock_btn" aria-hidden="true"></i>
                        <i class="flaticon-photo-camera upload_photo_btn" aria-hidden="true"></i>
                    </div>
                    <div class="comment_modal hidden">
                        <span>{{ __('cabinet.youtube_link') }}</span>
                        <input type="text" name="youtube_link" placeholder="{{ __('cabinet.paste_link') }}">
                        <button class="upload_btn upload_video_js">{{ __('cabinet.upload_video') }}</button>
                        <form method="post" class="ajax_form" action="{{ route('cabinet.addCommentImage') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <input type="hidden" name="comment_id" value="" />
                            <span>{{ __('cabinet.upload_image') }}</span>
                            <label class="label_upload" for="upload{{ $reply->id }}">{{ __('cabinet.choose_file') }}</label>
                            <input id="upload{{ $reply->id }}" class="upload_photo_input_js" type="file" accept="image/*" name="imgs[]" multiple hidden>
                            <input class="upload_btn" type="submit" value="{{ __('cabinet.upload') }}" />
                        </form>
                    </div>
                </div>

                @if($reply->parent->id == 0)
                    <div class="comment_btn send_btn send_btn_js">{{ __('home.comment_send') }}</div>
                    <div class="comment_btn cansel_btn ">{{ __('home.comment_cancel') }}</div>
                @endif
            </div>
        </div>

        @if($reply->parent->id == 0)
            <div class="comment_btn reply_btn">{{ __('home.comment_answer') }}</div>
        @endif
    @if($reply->replies->count())
        @include('home.partials.replies', ['replies' => $reply->replies])
    @endif
    </div>
@endforeach