routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::any('adminer', '\Miroc\LaravelAdminer\AdminerController@index')->name('adminer');  // admin db mysql 



Route::get('/p/{id}/{segment?}', 'ShowPost')->name('showpost');
Route::get('/showsearch', 'ShowSearch')->name('showsearch');


//Route::any('pas', 'Pas')->name('pas');

Route::group(
    [
        'middleware' => [
            'auth'
        ],
        'namespace' => 'Cabinet',
        'prefix'    => 'cabinet',
        'as' => 'cabinet.'
    ],
    function() {
        Route::get('/', ['as' => 'index', 'uses' => 'Index']);
        //Route::get('/showcatalog', ['as' => 'showcatalog', 'uses' => 'Index']);
        Route::get('/showcatalog/{slug1?}/{slug2?}', ['as' => 'showcatalog', 'uses' => 'ShowCatalog']);
        Route::get('/showcomments', ['as' => 'showcomments', 'uses' => 'ShowComments']);
        Route::get('/showrating', ['as' => 'showrating', 'uses' => 'ShowRating']);
        Route::get('/showfavorites/{slug1?}/{slug2?}', ['as' => 'showFavorites', 'uses' => 'ShowFavorites']);
        Route::get('/show-follows/{slug1?}/{slug2?}', ['as' => 'showFollows', 'uses' => 'ShowFollows']);

        Route::get('/user/follow', ['as' => 'follow', 'uses' => 'User\Follow']);
        Route::get('/user/unfollow', ['as' => 'unfollow', 'uses' => 'User\Unfollow']);
        Route::get('/user/is-private', ['as' => 'isprivate', 'uses' => 'User\IsPrivate']); //main.js
    

        Route::get('/get-last-items', ['as' => 'getLastItems', 'uses' => 'Photo\LastItems']);// main.js

        Route::post('/showcatalog/store', ['as'=>'dropzoneStore', 'uses'=>'Photo\DropzoneStore']);
        Route::post('/showcatalog/destroy', ['as'=>'dropzoneDestroy', 'uses'=>'Photo\DropzoneDestroy']);
        Route::post('/showcatalog/photomove', ['as'=>'dropzonePhotoMove', 'uses'=>'Photo\DropzonePhotoMove']);

        Route::post('/post/addposttofavorites', ['as'=>'addPostToFavorites', 'uses'=>'Post\AddPostToFavorites']);

        Route::post('/post/postlikeset', ['as'=>'postLikeSet', 'uses'=>'Post\PostLikeSet']);


        Route::post('/post/postdislikeset', ['as'=>'postDislikeSet', 'uses'=>'Post\PostDislikeSet']);


        Route::post('/post/postdisactive', ['as'=>'postDisActive', 'uses'=>'Post\PostDisActive']);


        Route::post('/comment/commentlikeset', ['as'=>'commentLikeSet', 'uses'=>'Comment\CommentLikeSet']);
        Route::post('/comment/commentdislikeset', ['as'=>'commentDislikeSet', 'uses'=>'Comment\CommentDislikeSet']);

        Route::post('/comment/update-comment', ['as'=>'updateComment', 'uses'=>'Comment\UpdateComment']);
        Route::post('/comment/add-comment-image', ['as'=>'addCommentImage', 'uses'=>'Comment\AddCommentImage']);

        Route::post('/comment/mark-as-viewed', ['as'=>'markAsViewed', 'uses'=>'Comment\MarkAsViewed']);

        Route::post('/post/updatepostcomment', ['as'=>'updatePostComment', 'uses'=>'Post\UpdatePostComment']);
        Route::post('/post/addcommentimage', ['as'=>'addPostCommentImage', 'uses'=>'Post\AddCommentImage']);
    }
);


//todo повесить middleware "ни для кого" - 404?
Route::resource('photos', 'Cabinet\Photo\Resource');

Route::delete('/tags', 'Cabinet\Tag\Resource@destroy');
Route::resource('tags', 'Cabinet\Tag\Resource');

Route::resource('comments', 'Cabinet\Comment\Resource');


// Route::get('/login-as/{login}', function ($login)
// {
//     switch ($login)
//     {
//         case 'lolik_89':
//             session(['clientId' => '64d03de3ea344a31b7fa496d0c9b6df2']);
//             session(['clientSecret' => '884be34ffbd54c308f38193ee757ee9f']);
//             break;
//         case 'artem.stepochkin':
//             session(['clientId' => 'b00a737d5e24463a9bdf425a5c452125']);
//             session(['clientSecret' => 'a5be9c22f25b445ab66a7273033e0008']);
//             break;
//         case 'v.voloshyn96':
//             session(['clientId' => '768aa50b31154e99b58bd3c2e002a0f5']);
//             session(['clientSecret' => '5b83c79bcd04476e87bc7f73648a6f60']);
//             break;
//         default: break;
//     }
//     return redirect()->back();
//     //return redirect()->route('socialAuth', 'instagram');
// });


Auth::routes();    //all  !!!!!





//OAuth routes
Route::get('auth/{driver}', ['as' => 'socialAuth', 'uses' => 'Auth\Social@redirectToProvider']);
Route::get('auth/{driver}/callback', ['as' => 'socialAuthCallback', 'uses' => 'Auth\Social@handleProviderCallback']);

Route::get('/setlocale/{locale}', function ($locale) {
    $locale = (\Illuminate\Support\Facades\File::isDirectory('../resources/lang/'.$locale)) ? $locale : App::getLocale();
    session(['lang' => $locale]);
    return redirect()->back();
});

Route::get('/{slug1?}/{slug2?}/{slug3?}/{slug4?}', 'Index')->name('index');  // SearchController

//Route::get('/REMOVE_THIS_ROUTE', 'ShowProfile')->name('showprofile');

app/Http/Controllers/Cabinet/Comment/AddCommentImage.php
<?php

namespace App\Http\Controllers\Cabinet\Comment;

use App\Models\Comment;
use App\Models\Photo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;

class AddCommentImage extends Controller
{
    public function __invoke(Request $request)
    {
        if($request->hasFile('imgs'))
        {
            $comment = Comment::findOrFail($request->comment_id);
            $images = $request->file('imgs');
            $srcs = [];

            $i = 0;
            foreach ($images as $image)
            {
                if (in_array($image->extension(), Photo::EXTENSIONS) && $image->getClientSize() <= Photo::MAX_FILE_SIZE)
                {
                    $photoId = $comment->saveImage($image);
                    $photo = Photo::findOrFail($photoId);
                    $srcs[$i]['thumb'] = $photo->getThumbnailSrc();
                    $srcs[$i]['full'] = $photo->getImageSrc();
                    $i++;
                }
                else return response()->json(['error'=> __('layout.large_image'), 'label'=> __('cabinet.choose_file')]);
            }
            return response()->json(['srcs'=>$srcs, 'label'=> __('cabinet.choose_file')]);
        }
        else return '$request->hasFile(\'imgs\') was return false';
    }
}

app/Http/Controllers/Cabinet/Comment/CommentDislikeSet.php
<?php

namespace App\Http\Controllers\Cabinet\Comment;

use App\Events\onCommentRatingDownSet;
use App\Events\onCommentRatingDownUnset;
use App\Events\onCommentRatingUpUnset;
use App\Models\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

/**
 * Class CommentDislikeSet
 * @package App\Http\Controllers\Cabinet\Comment
 */
class CommentDislikeSet extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function __invoke(Request $request)
    {
        $user = Auth::user();
        $comment = Comment::findOrFail($request->comment_id);
        $message = '';
        if ($comment->isUserDislikeFound())
        {
            event(new onCommentRatingDownUnset($comment, $user));
            $message = __('layout.dislike.unset');
        }
        else
        {
            event(new onCommentRatingDownSet($comment, $user));
            $message = __('layout.dislike.set');
        }

        if ($comment->isUserLikeFound())
        {
            event(new onCommentRatingUpUnset($comment, $user));
        }

        return response()->json(['status' => 'success', 'message' => $message, 'rating' => $comment->rating]);
    }
}

app/Http/Controllers/Cabinet/Comment/CommentLikeSet.php
<?php

namespace App\Http\Controllers\Cabinet\Comment;

use App\Events\onCommentRatingDownUnset;
use App\Events\onCommentRatingUpSet;
use App\Events\onCommentRatingUpUnset;
use App\Models\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

/**
 * Class CommentLikeSet
 * @package App\Http\Controllers\Cabinet\Comment
 */
class CommentLikeSet extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function __invoke(Request $request)
    {
        $user = Auth::user();
        $comment = Comment::findOrFail($request->comment_id);

        $message = '';
        if ($comment->isUserLikeFound())
        {
            event(new onCommentRatingUpUnset($comment, $user));
            $message = __('layout.like.unset');
        }
        else
        {
            event(new onCommentRatingUpSet($comment, $user));
            $message = __('layout.like.set');
        }

        if ($comment->isUserDislikeFound())
        {
            event(new onCommentRatingDownUnset($comment, $user));
        }

      //  dd();
        return response()->json(['status' => 'success', 'message' => $message, 'rating' => $comment->rating]);
    }
}

app/Http/Controllers/Cabinet/Comment/MarkAsViewed.php
<?php

namespace App\Http\Controllers\Cabinet\Comment;

use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MarkAsViewed extends Controller
{
    public function __invoke(Request $request)
    {
        $comment = Comment::findOrFail($request->comment_id);
        $comment->viewed = 1;
        $comment->save();

        return redirect()->back();
    }
}

app/Http/Controllers/Cabinet/Comment/Resource.php
<?php

namespace App\Http\Controllers\Cabinet\Comment;

use App\Http\Requests\CommentStoreRequest;
use App\Models\Comment as CommentModel;
use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\Photo;

class Resource extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CommentStoreRequest $request)
    {
        if($request->isMethod('post') && $request->has('post_id') && $request->has('comment'))
        {
            $parent_id = (int)$request->parent_id;

            $post = Post::where('id', $request->post_id)->firstOrFail();

            $parentComment = null;
            if ($parent_id)
            {
                $parentComment = Comment::findOrFail($parent_id);
            }

            $userId = $parentComment ? $parentComment->user_id : $post->user_id;


                $comment = $post->comments()->create([
                    'is_from_instagram'=> 0,
                    'content'=> (string)$request->input('comment'),
                    'parent_id' => $parent_id,
                    'user_to_id' => $userId,
                    'user_id' => Auth::user()->id,
                ]);

                $response = [
                    'html' => view('home.partials.comment', ['comment'=>$comment, 'parent_id'=> $parent_id, 'post'=>$post])->render(),
                    'id' => $comment->id,
                ];
                return response()->json($response);

                /*
                if ($request->hasFile('photo') && $request->file('photo')->isValid())
                {
                    $commentImage = $request->photo;
                    $comment->saveImage($commentImage);
                }*/
        }

        //return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(CommentModel $comment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(CommentModel $comment)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CommentModel $comment)
    {
        $data = $request->except('_token');

        $comment->content = $data['comment'];
        $comment->save();
		$parent = $comment->parent()->first();
        $parent_id = empty($parent) ? 0 : $parent->id;
        $post = $comment->post;

        $response = [
            'html' => view('home.partials.comment', ['comment'=>$comment, 'parent_id'=> $parent_id, 'post'=>$post])->render(),
            'id' => $comment->id,
        ];
        return response()->json($response);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(CommentModel $comment)
    {
        if ($comment->delete())
            return 'SERVER delete ok';
        else return 'SERVER ERROR DELETING';
    }
}

app/Http/Controllers/Cabinet/Comment/UpdateComment.php
<?php

namespace App\Http\Controllers\Cabinet\Comment;

use App\Models\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UpdateComment extends Controller
{
    public function __invoke(Request $request)
    {
        /*
        $files = File::allFiles(public_path().$path);

        $srcs = [];
        foreach ($files as $file)
        {
            $srcs[] = $path . $file->getFilename();
        }
        return $srcs;
        */

        $content = $request->input('content');
        $commentId = $request->comment_id;

        $comment = Comment::findOrFail($commentId);

        $comment->content = $content;
        $comment->save();

        return 'server ok';
    }
}

app/Http/Controllers/Cabinet/Index.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Events\onAddPostToFavouritesEvent;
use App\Models\Comment;
use App\Models\Post;
use App\Models\Photo;

use Andreyco\Instagram\Support\Laravel\Facade\Instagram;
use App\Models\PostDescription;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

use App\Services\InstagramWrapper;

class Index extends Controller
{
    public function __invoke(Request $request)
    {
////
//        Instagram::setAccessToken(session('access_token'));
//
//        $media = Instagram::getUserMedia();
//        dump($media);

//        $post = Post::find(1);
//
//        $part = $post->getLinkPart();
//        $fullFromPart = $post->getLinkFromPart($part);

//
//        if (isset($media->pagination->next_url))
//            dump('yes');
//        else dump('no');
//



        //dd('Cabinet end.');

        //dd($media);

        //$photo = Photo::findOrFail(2);
        //dd($photo->deleteImage());

        //$post = Post::findOrFail(1);

        //event(new onAddPostToFavouritesEvent($post, $user));
        //dump($user->favorites);

        //$text1 = PostDescription::find(1)->content;

//        $text2 = PostDescription::find(2);
//        $text3 = PostDescription::find(3);
//        $text100 = PostDescription::find(3);

        //$result = clean($text1, 'post-description');

        //dump($text1, $result);

        //$value = '<br>';
        //$value = clean($value, 'post_description');
        //dd($value);

        /*
         *
         * Конец полигона
         *
         */

        //$posts = $user->posts();

        $user = Auth::user();

        $data = [
            'user'=>$user,
            //'posts'=>$posts->get(),
        ];
        return view('cabinet.index', $data);
    }
}

app/Http/Controllers/Cabinet/Photo/DropzoneDestroy.php
<?php

namespace App\Http\Controllers\Cabinet\Photo;

use App\Http\Requests\DropzoneDestroyRequest;
use App\Models\Photo;
use App\Services\CalculateRatingsService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DropzoneDestroy extends Controller
{
    public function __invoke(DropzoneDestroyRequest $request)
    {
        $photo = Photo::findBySrc($request->src);

        if ($photo)
        {
            $post = $photo->photable;

            if ($photo->hasImage())
            {
                $photo->deleteImage();
            }
            $photo->delete();

            if (empty($post->description->content) && !$post->getPhotosCount())
            {
                $post->is_empty = 1;
                $post->save();
                CalculateRatingsService::calculateUserRating($post->user);
            }

            $message = 'delete ok';
        }
        else $message = 'error deleting!'; //todo localize

        return response()->json($message);
    }
}

app/Http/Controllers/Cabinet/Post/Addaboutme.php
<?php

namespace App\Http\Controllers\Cabinet\Post;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class Addaboutme extends Controller
{
    //
}

app/Http/Controllers/Cabinet/Post/ShowPost.php
<?php

namespace App\Http\Controllers\Cabinet\Post;

use Illuminate\Http\Request;

class ShowPost extends Controller
{
    public function __invoke()
    {
        return view('index');
    }
}

resources/views/cabinet/partials/last-synced-items.blade.php
<div class="last-synced-items {{ count($lastPosts) == 0 ? 'in-progress' : '' }}">
    <h2>lAst-synced-ITEM {{ __('cabinet.latest_widget_header') }}</h2>

    <div class="posts owl-carousel owl-theme">
        @if(count($lastPosts))
            @foreach ($lastPosts as $lastPost)
                @foreach ($lastPost->photos() as $lastPhoto)
                    <a href="{{ route('showpost', $lastPost->getLinkPart()) }}">
                        <div class="item">
                        <img src="{{ $lastPhoto->getThumbnailSrc() }}" alt="inst_img">
                        <span class="date">{{ \Carbon\Carbon::parse($lastPhoto->updated_at)->diffForHumans(null, false, true) }}</span>
                        </div>
                    </a>
                @endforeach
            @endforeach
        @endif
    </div>
</div>

resources/views/cabinet/partials/pagination-item.blade.php
@foreach($posts as $post)
<div class="post">
    <div class="post_item_block instagram_photo">
        <h2 class="post_title_item_mob">RRRRRRR{{ __('cabinet.instagram') }}</h2>
        @include('layouts.partials.icons', ['post'=>$post])
        <div class="photo">
            <div class="photo_wrap">
                @foreach($post->instagramPhotos()->get() as $photo)
                    @if($photo->isInstagramImage())
                        {{--                                    <img {{ $side['isEqual'] ? '' : $side['biggestSide'] . '=' . '' . $side['number'] . '' }} src="{{ $photo->getImageSrc() }}" alt="inst_img">--}}
                        <img src="{{ $photo->getImageSrc() }}" alt="inst_img">
                    @endif
                    @if($photo->isInstagramCarousel())
                        <div class="owl-carousel owl-theme instagram_slider">
                            @foreach($photo->getInstagramCarouselSrcs() as $src)
                                <div class="slider-item">
                                    {{--<img {{ $side['isEqual'] ? '' : $side['biggestSide'] . '=' . '' . $side['number'] . '' }} src="{{ $src }}" alt="inst_img">--}}
                                    <img class="owl-lazy" data-src="{{ $src }}" src="{{ $src }}" alt="inst_img">
                                </div>
                            @endforeach
                        </div>
                        <div class="instagram_album_ico">
                            <i class="fa fa-clone" aria-hidden="true"></i>
                        </div>
                    @endif
                @endforeach
            </div>
            @include('layouts.partials.photo-info', ['post'=>$post])
        </div>
    </div>
    <div class="post_item_block add_photos">
        <h2 class="post_title_item_mob">{{ __('home.additional_photo') }} <span>{{ __('cabinet.max_photo', ['count'=>\App\Models\Post::MAX_PHOTOS]) }}</span></h2>
        <form id="dropzone{{ $post->id }}" action="{{ route('cabinet.dropzoneStore') }}" method="post" class="drop_zone {{ $post->imagePhotos()->count() ? '' : 'empty' }}" enctype="multipart/form-data">
            <input type="hidden" name="post_id" value="{{ $post->id }}">
            {{ csrf_field() }}
            @forelse($post->imagePhotos()->get() as $photo)
                <div class="add_img_wrap dragbox">
                    <img class="dragbox-content" src="{{ $photo->getThumbnailSrc() }}" alt="inst_img" data-id="{{ $photo->id }}">                               <span class="del_photos"><i class="fa fa-times" aria-hidden="true"></i></span>
                </div>
            @empty
            @endforelse
            <div class="dz-default dz-message drop_zone_message add_img_wrap">
                <div class="drop_zone_ico">+</div>
                <span class="drop_desk_text">{{ __('cabinet.drag_and_drop') }}</span>
                <span class="drop_mob_text">{{ __('cabinet.add_photo') }}</span>
            </div>
            <div class="loader hidden"><div class="spiner"></div></div>
        </form>
        <div class="error hidden">
            <span></span> {{ __('cabinet.big_file_text') }}
        </div>
    </div>
    <div class="post_item_block comment">
        <h2 class="post_title_item_mob">{{ __('cabinet.comment') }} <span>{{ __('cabinet.write_comment') }}</span></h2>
        <div class="comment_block">
            {{ csrf_field() }}
            <input type="hidden" name="post_id" value="{{ $post->id }}">
            <div class="text_container" contenteditable="true">
                {!! $post->description->content !!}
            </div>
            <div class="comment_action_block">
                <div class="comment_action_icons hidden">
                    <i class="flaticon-piggy-bank" aria-hidden="true"></i>
                    <i class="flaticon-musical-note" aria-hidden="true"></i>
                    <i class="flaticon-chat" aria-hidden="true"></i>
                    <i class="flaticon-headphones" aria-hidden="true"></i>
                </div>
                <div class="comment_action_btn_block">
                    <span class="send_comment_btn">отправить</span>
                    <i class="flaticon-smile smiles_dock_btn" aria-hidden="true"></i>
                    <i class="flaticon-photo-camera upload_photo_btn" aria-hidden="true"></i>
                </div>
                <div class="comment_modal hidden">
                    <span>{{ __('cabinet.youtube_link') }}</span>
                    <input type="text" name="youtube_link" placeholder="{{ __('cabinet.paste_link') }}">
                    <button class="upload_btn upload_video_js">{{ __('cabinet.upload_video') }}</button>
                    <form method="post" class="ajax_form" action="{{ route('cabinet.addPostCommentImage') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <input type="hidden" name="post_id" value="{{ $post->id }}" />
                        <span>{{ __('cabinet.upload_image') }}</span>
                        <label class="label_upload" for="upload{{ ($post->id == 1) ? '' : $post->id }}">{{ __('cabinet.choose_file') }}</label>
                        <input id="upload{{ ($post->id == 1) ? '' : $post->id }}" class="upload_photo_input_js" type="file" accept="image/*" name="imgs[]" multiple hidden>
                        <input class="upload_btn" type="submit" value="{{ __('cabinet.upload') }}" />
                    </form>
                </div>
            </div>
        </div>
        <input class="tags_input_js" type="text" value="{{ $post->getTagsStr() }}" data-role="tagsinput" placeholder="{{ __('cabinet.add_tag') }}" />
    </div>
</div>
@endforeach

resources/views/cabinet/partials/private-profile-info.blade.php
<div class="private-profile-info">
    <h2>rrrrrrrrrrrrrrrrr{{ __('cabinet.private_profile_header') }}</h2>

    <div class="content">
        <img style="max-width: 100%; height: auto;" src="/img/private-info.png"/>

        <div class="check_again">
            <button class="check_again_btn">43536{{ __('cabinet.private_profile_check') }}</button>
        </div>
    </div>
</div>

resources/views/cabinet/partials/profilemenu.blade.php
    <div class="profile_menu">

        <div>
            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="flaticon-logout" aria-hidden="true"></i>{{ __('cabinet.exit') }}
            </a>
        </div>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>

        <div>
            <a href="{{ route('cabinet.showFavorites') }}"><i class="flaticon-heart" aria-hidden="true"></i>{{ __('cabinet.favorites') }}
            </a>
        </div>
        <div>
            <a style="position: relative" href="{{ route('cabinet.showFollows') }}"><i class="flaticon-commerce" aria-hidden="true"></i>{{ __('cabinet.follows') }}
                @if($count = Auth::user()->followedUsers()->count())
                    <div class="be_bage">{{ $count }}</div>
                @endif
            </a>
        </div>
        {{--({{ Auth::user()->followedUsers()->count() }})--}}
    </div>